version: "3"

services:
  bot:
    image: ghcr.io/tuna2134/globalchat-rs
    build: .
    container_name: globalchat-rs
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.1"
    env_file: ./.env
    restart: always